version: "3.7"

services:
  # 명칭 설정
  start-express:
    environment:
      # 시간 설정
      TZ: "Asia/Seoul"
    # docker container 이름 설정
    container_name: start-express
    # docker image 이름 설정
    image: start-express-image
    build:
      context: .
      # 빌드시 사용할 docker 파일 설정
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      # 외부 포트 : 내부포트 하나만 적을시 도커내부만 접근가능
      - 8081:4000

volumes:
  data:
    driver: local
# 추가 네트워크 설정
networks:
  default:
    external:
      name: dizzy
